name: Test
on:
  push:
    branches:
      - main
      - 'peah/*'
  pull_request:
    branches:
      - main
  
  milestone:
    types:
      - closed

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources 
        uses: actions/checkout@v4
      
      - name: Create a Release draft for a milestone
        id: create-release-draft
        uses: ./ # Uses an action in the root directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo-token: ${{ github.ref }}
    
      - name: Print the url for the release draft
        if: steps.create-release-draft.outputs.release-url != ''
        run: echo "${{ steps.create-release-draft.outputs.release-url }}"

