name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
  milestone:
    types:
      - closed

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: ./ # Uses an action in the root directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo-token: ${{ github.ref }}
    
      - name: Get the release URL
        run: echo "The release URL is ${{ steps.create_release.outputs.html_url }}"
