name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
  milestone:
    types:
      - closed

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Get the release URL
        run: echo "The release URL is ${{ steps.create_release.outputs.html_url }}"
