name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
  milestone:
    types:
      - closed

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create the Release draft for a milestone
        id: create-release-draft
        uses: ./ # Uses an action in the root directory
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Print the url of the release draft
        if: steps.create-release-draft.outputs.release_url != ''
        run: echo  ${{ steps.create-release-draft.outputs.release_url }}"
